spring:
  datasource:
    url: ${DATA_BASE_URL:jdbc:h2:mem:mydb}
    username: ${DATA_USERNAME:sa}
    password: ${DATA_USER_PASSWORD:password}
    driverClassName: ${DATA_DRIVER:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: ${DATA_BASE_PLATFORM:org.hibernate.dialect.H2Dialect}
  flyway:
    enabled: true
    clean-on-validation-error: true
    baseline-on-migrate: true
  cache:
    type: redis
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
      time-to-live: 3600s

logging:
  level:
    root: info
  file:
    name: LogFile.log

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always

application:
  client:
    local:
      url: http://localhost:8081
    heroku:
      url: https://user-info.herokuapp.com